services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports: ["8086:8086"]
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: jspX
      DOCKER_INFLUXDB_INIT_BUCKET: scada
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports: ["3000:3000"]
    restart: unless-stopped
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports: ["1880:1880"]
    restart: unless-stopped
    volumes:
      - ./nodered/data:/data
    environment:
      - INFLUXDB_WRITE_TOKEN=${INFLUXDB_WRITE_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
    depends_on: [influxdb]

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports: ["1883:1883"]
    restart: unless-stopped
    volumes:                            # Persist and inject config/data for reproducibility
      - ./mqtt/config/mqtt.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  sim:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mosquitto
    restart: unless-stopped
    environment:
      - BROKER_URL= ${MQTT_BROKER_URL}
      - PUB_TOPIC= ${MQTT_PUB_TOPIC}
      - CMD_TOPIC= ${MQTT_CMD_TOPIC}
      - RESET_TOPIC= ${MQTT_RESET_TOPIC}
      - STATUS_TOPIC= ${MQTT_STATUS_TOPIC}
      - RATE_HZ= ${SIM_RATE_HZ}
    command:
      - python
      - src/power_sim.py
      - --mqtt
      - --pandapower
      - --host
      - mosquitto         


volumes:
  influxdb-data:  
  influxdb-config:
  grafana-data: