apiVersion: 1
datasources:
  - name: InfluxDB
    uid: P951FEA4DE68E13C5
    type: influxdb
    access: proxy
    isDefault: true
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: $INFLUXDB_READ_TOKEN
